# Generated by Django 4.2.7 on 2023-11-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
    ]
