# Generated by Django 4.2.7 on 2023-11-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0005_alter_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playliststack',
            name='song_id',
        ),
        migrations.AddField(
            model_name='playliststack',
            name='song_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jukebox.song'),
            preserve_default=False,
        ),
    ]
